export const SEED_BIKES = [
  // Mountain — Hardtail
  {
    id: 'trek-marlin-7',
    brand: 'Trek',
    model: 'Marlin 7',
    year: 2024,
    type: 'mountain',
    subtype: 'trail',
    msrp: 1049,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '29"',
    suspension_type: 'hardtail',
    weight_range: '30–32 lbs',
    best_for: ['beginner', 'trail', 'budget'],
    karma_score: 55,
    notes: 'Best-selling trail hardtail. Reliable Shimano drivetrain, available everywhere.',
  },
  {
    id: 'marin-bobcat-trail-3',
    brand: 'Marin',
    model: 'Bobcat Trail 3',
    year: 2024,
    type: 'mountain',
    subtype: 'trail',
    msrp: 799,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '29"',
    suspension_type: 'hardtail',
    weight_range: '31–33 lbs',
    best_for: ['beginner', 'value', 'trail'],
    karma_score: 52,
    notes: 'Excellent value hardtail from an independent brand. Great first mountain bike.',
  },
  {
    id: 'giant-talon-1',
    brand: 'Giant',
    model: 'Talon 1',
    year: 2024,
    type: 'mountain',
    subtype: 'trail',
    msrp: 870,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '29"',
    suspension_type: 'hardtail',
    weight_range: '30–32 lbs',
    best_for: ['beginner', 'trail'],
    karma_score: 54,
    notes: "Giant's aluminum is industry-leading quality. Solid entry hardtail.",
  },
  {
    id: 'trek-roscoe-8',
    brand: 'Trek',
    model: 'Roscoe 8',
    year: 2024,
    type: 'mountain',
    subtype: 'trail',
    msrp: 1699,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '27.5"',
    suspension_type: 'hardtail',
    weight_range: '31–33 lbs',
    best_for: ['intermediate', 'trail', 'playful'],
    karma_score: 55,
    notes: 'Plus-width tires give extra grip. Fun, playful hardtail for intermediate riders.',
  },
  {
    id: 'santa-cruz-chameleon',
    brand: 'Santa Cruz',
    model: 'Chameleon',
    year: 2024,
    type: 'mountain',
    subtype: 'trail',
    msrp: 2199,
    frame_material: 'aluminum',
    drivetrain_brand: 'SRAM',
    drivetrain_type: 'mechanical',
    wheel_size: '29"',
    suspension_type: 'hardtail',
    weight_range: '28–30 lbs',
    best_for: ['intermediate', 'trail', 'bikepacking'],
    karma_score: 71,
    notes: 'Santa Cruz quality in a versatile hardtail. Made in Santa Cruz, CA. Upgradeable.',
  },

  // Mountain — Full Suspension Trail
  {
    id: 'santa-cruz-bronson',
    brand: 'Santa Cruz',
    model: 'Bronson',
    year: 2024,
    type: 'mountain',
    subtype: 'trail',
    msrp: 3999,
    frame_material: 'aluminum',
    drivetrain_brand: 'SRAM',
    drivetrain_type: 'mechanical',
    wheel_size: '29"',
    suspension_type: 'full',
    weight_range: '29–33 lbs',
    best_for: ['intermediate', 'trail', 'enduro'],
    karma_score: 71,
    notes: 'Legendary trail bike. 150mm travel, handles everything.',
  },
  {
    id: 'trek-slash-8',
    brand: 'Trek',
    model: 'Slash 8',
    year: 2024,
    type: 'mountain',
    subtype: 'enduro',
    msrp: 4499,
    frame_material: 'aluminum',
    drivetrain_brand: 'SRAM',
    drivetrain_type: 'mechanical',
    wheel_size: '29"',
    suspension_type: 'full',
    weight_range: '31–34 lbs',
    best_for: ['experienced', 'enduro', 'aggressive'],
    karma_score: 55,
    notes: '160mm enduro weapon. For riders who want to go fast and rough.',
  },
  {
    id: 'ibis-ripmo',
    brand: 'Ibis',
    model: 'Ripmo AF',
    year: 2024,
    type: 'mountain',
    subtype: 'trail',
    msrp: 3999,
    frame_material: 'aluminum',
    drivetrain_brand: 'SRAM',
    drivetrain_type: 'mechanical',
    wheel_size: '29"',
    suspension_type: 'full',
    weight_range: '30–33 lbs',
    best_for: ['intermediate', 'trail', 'enduro'],
    karma_score: 74,
    notes: "Ibis is worker-friendly and independent. 'AF' = Aluminum Frame. Outstanding value.",
  },

  // Road
  {
    id: 'specialized-allez',
    brand: 'Specialized',
    model: 'Allez',
    year: 2024,
    type: 'road',
    subtype: null,
    msrp: 900,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '19–21 lbs',
    best_for: ['beginner', 'training', 'value'],
    karma_score: 58,
    notes: "Specialized's E5 aluminum frame punches above its price. The classic entry road bike.",
  },
  {
    id: 'trek-domane-al-3',
    brand: 'Trek',
    model: 'Domane AL 3',
    year: 2024,
    type: 'road',
    subtype: null,
    msrp: 1299,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '20–22 lbs',
    best_for: ['beginner', 'endurance', 'comfort'],
    karma_score: 55,
    notes: 'IsoSpeed decoupler reduces road vibration. Great endurance geometry.',
  },
  {
    id: 'specialized-roubaix-sport',
    brand: 'Specialized',
    model: 'Roubaix Sport',
    year: 2024,
    type: 'road',
    subtype: null,
    msrp: 2500,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '20–22 lbs',
    best_for: ['intermediate', 'endurance', 'long_rides'],
    karma_score: 58,
    notes: 'Future Shock front suspension. Made for long days in the saddle.',
  },
  {
    id: 'trek-emonda-alr-4',
    brand: 'Trek',
    model: 'Émonda ALR 4',
    year: 2024,
    type: 'road',
    subtype: null,
    msrp: 1999,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '18–20 lbs',
    best_for: ['intermediate', 'climbing', 'racing'],
    karma_score: 55,
    notes: "Trek's lightweight aluminum climber. Aggressive geometry, race-ready.",
  },

  // Gravel
  {
    id: 'marin-four-corners',
    brand: 'Marin',
    model: 'Four Corners',
    year: 2024,
    type: 'gravel',
    subtype: null,
    msrp: 1399,
    frame_material: 'chromoly',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '23–25 lbs',
    best_for: ['intermediate', 'adventure', 'bikepacking'],
    karma_score: 52,
    notes: 'Chromoly steel gravel bike with rack/fender mounts. Built to be loaded and ridden far.',
  },
  {
    id: 'trek-checkpoint-alr-5',
    brand: 'Trek',
    model: 'Checkpoint ALR 5',
    year: 2024,
    type: 'gravel',
    subtype: null,
    msrp: 2599,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '20–22 lbs',
    best_for: ['intermediate', 'gravel', 'adventure'],
    karma_score: 55,
    notes: 'IsoSpeed gravel geometry. Can run 45mm tires. Great for mixed-surface riding.',
  },
  {
    id: 'specialized-diverge-comp',
    brand: 'Specialized',
    model: 'Diverge Comp',
    year: 2024,
    type: 'gravel',
    subtype: null,
    msrp: 3000,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '21–23 lbs',
    best_for: ['experienced', 'gravel', 'racing'],
    karma_score: 58,
    notes: 'Future Shock suspension stem. Fast geometry. Serious gravel machine.',
  },

  // Bikepacking / Touring
  {
    id: 'surly-long-haul-trucker',
    brand: 'Surly',
    model: 'Long Haul Trucker',
    year: 2024,
    type: 'touring',
    subtype: null,
    msrp: 1699,
    frame_material: 'chromoly',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '26"',
    suspension_type: 'rigid',
    weight_range: '27–29 lbs',
    best_for: ['touring', 'loaded', 'bikepacking'],
    karma_score: 78,
    notes: 'The gold standard touring bike. Chromoly steel, triple chainring, load-bearing geometry.',
  },
  {
    id: 'salsa-fargo',
    brand: 'Salsa',
    model: 'Fargo',
    year: 2024,
    type: 'touring',
    subtype: null,
    msrp: 2499,
    frame_material: 'chromoly',
    drivetrain_brand: 'SRAM',
    drivetrain_type: 'mechanical',
    wheel_size: '29"',
    suspension_type: 'rigid',
    weight_range: '26–28 lbs',
    best_for: ['bikepacking', 'adventure', 'off-road-touring'],
    karma_score: 65,
    notes: '29" wheels handle rough roads. Drop bars + mountain bike geometry for remote adventure.',
  },
  {
    id: 'trek-520',
    brand: 'Trek',
    model: '520',
    year: 2024,
    type: 'touring',
    subtype: null,
    msrp: 1999,
    frame_material: 'chromoly',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '26–28 lbs',
    best_for: ['touring', 'loaded', 'long-distance'],
    karma_score: 55,
    notes: "Trek's touring icon. Bombproof chromoly, triple chainring, worldwide parts availability.",
  },

  // Commuter
  {
    id: 'trek-fx-3-disc',
    brand: 'Trek',
    model: 'FX 3 Disc',
    year: 2024,
    type: 'commuter',
    subtype: null,
    msrp: 979,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '21–23 lbs',
    best_for: ['commuting', 'fitness', 'urban'],
    karma_score: 55,
    notes: 'Versatile flat-bar road bike. Fast, light, accepts fenders and racks.',
  },
  {
    id: 'specialized-sirrus-3',
    brand: 'Specialized',
    model: 'Sirrus 3.0',
    year: 2024,
    type: 'commuter',
    subtype: null,
    msrp: 1150,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '22–24 lbs',
    best_for: ['commuting', 'fitness', 'urban'],
    karma_score: 58,
    notes: 'Upright, comfortable geometry. Disc brakes. Great fitness commuter.',
  },

  // E-bike
  {
    id: 'trek-allant-7',
    brand: 'Trek',
    model: 'Allant+ 7',
    year: 2024,
    type: 'ebike',
    subtype: 'commuter',
    msrp: 3799,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '48–52 lbs',
    best_for: ['commuting', 'fitness', 'urban', 'cargo'],
    karma_score: 55,
    notes: 'Bosch motor. Up to 85mi range. Integrated lights and rack. Class 1 (20mph assist).',
  },
  {
    id: 'trek-rail-9-7',
    brand: 'Trek',
    model: 'Rail 9.7',
    year: 2024,
    type: 'ebike',
    subtype: 'mountain',
    msrp: 6499,
    frame_material: 'carbon',
    drivetrain_brand: 'SRAM',
    drivetrain_type: 'electronic',
    wheel_size: '29"',
    suspension_type: 'full',
    weight_range: '49–52 lbs',
    best_for: ['trail', 'experienced', 'ebike-mtb'],
    karma_score: 55,
    notes: 'Bosch CX motor, 150mm travel. Ride more trail, recover faster. Class 1.',
  },
  {
    id: 'specialized-vado-sl-4',
    brand: 'Specialized',
    model: 'Vado SL 4.0',
    year: 2024,
    type: 'ebike',
    subtype: 'commuter',
    msrp: 3500,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '700c',
    suspension_type: 'rigid',
    weight_range: '33–36 lbs',
    best_for: ['commuting', 'fitness', 'lightweight-ebike'],
    karma_score: 58,
    notes: "Specialized's own SL 1.1 motor. Lightest class of e-bike. 80mi range. Feels like a 'real' bike.",
  },

  // Kids
  {
    id: 'trek-precaliber-20',
    brand: 'Trek',
    model: 'Precaliber 20',
    year: 2024,
    type: 'kids',
    subtype: null,
    msrp: 459,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '20"',
    suspension_type: 'rigid',
    weight_range: '19–21 lbs',
    best_for: ['kids', 'ages-6-10'],
    karma_score: 55,
    notes: 'Kid-specific geometry. Light enough for small riders. Disc brakes on higher trims.',
  },
  {
    id: 'coop-rev-20',
    brand: 'Co-op Cycles',
    model: 'REV 20',
    year: 2024,
    type: 'kids',
    subtype: null,
    msrp: 299,
    frame_material: 'aluminum',
    drivetrain_brand: 'Shimano',
    drivetrain_type: 'mechanical',
    wheel_size: '20"',
    suspension_type: 'rigid',
    weight_range: '20–22 lbs',
    best_for: ['kids', 'ages-6-10', 'value'],
    karma_score: 72,
    notes: "REI Co-op brand. Co-op ownership model. Great value kids bike from a trustworthy source.",
  },
];

export function getBikesByType(type) {
  return SEED_BIKES.filter(b => b.type === type);
}

export function getBikesByBudget(msrpMax) {
  return SEED_BIKES.filter(b => b.msrp <= msrpMax);
}
