export const SEED_SHOPS = [
  {
    id: 'bicycle-cellar',
    name: 'Bicycle Cellar',
    address: '532 Farmington Ave',
    city: 'Unionville',
    state: 'CT',
    zip: '06085',
    lat: 41.7412,
    lng: -72.9121,
    phone: '(860) 675-2453',
    website: 'https://bicyclecellar.com',
    email: null,
    brands_carried: ['Trek', 'Specialized', 'Cannondale', 'Shimano', 'SRAM'],
    services: ['repair', 'custom_builds', 'wheel_building', 'fitting', 'rental'],
    shop_type: 'indie',
    verified: true,
  },
  {
    id: 'pedal-power-hartford',
    name: 'Pedal Power',
    address: '1171 New Britain Ave',
    city: 'Hartford',
    state: 'CT',
    zip: '06110',
    lat: 41.7514,
    lng: -72.7454,
    phone: '(860) 953-0001',
    website: null,
    email: null,
    brands_carried: ['Giant', 'Raleigh', 'Electra', 'Shimano'],
    services: ['repair', 'rental'],
    shop_type: 'indie',
    verified: true,
  },
  {
    id: 'cycle-loft-greenwich',
    name: 'Cycle Loft',
    address: '33 Valley Dr',
    city: 'Greenwich',
    state: 'CT',
    zip: '06831',
    lat: 41.0243,
    lng: -73.6354,
    phone: '(203) 869-4141',
    website: 'https://cycleloft.com',
    email: null,
    brands_carried: ['Specialized', 'Trek', 'Cervelo', 'Pinarello', 'Shimano', 'SRAM'],
    services: ['repair', 'fitting', 'wheel_building', 'custom_builds'],
    shop_type: 'indie',
    verified: true,
  },
  {
    id: 'benidorm-bikes',
    name: 'Benidorm Bikes',
    address: '62 LaSalle Rd',
    city: 'West Hartford',
    state: 'CT',
    zip: '06107',
    lat: 41.7623,
    lng: -72.7374,
    phone: '(860) 521-2453',
    website: 'https://benidormbikes.com',
    email: null,
    brands_carried: ['Trek', 'Giant', 'Cannondale', 'Shimano', 'SRAM', 'Fox'],
    services: ['repair', 'fitting', 'wheel_building'],
    shop_type: 'indie',
    verified: true,
  },
  {
    id: 'route-44-cycles',
    name: 'Route 44 Cycles',
    address: '265 West Main St',
    city: 'Avon',
    state: 'CT',
    zip: '06001',
    lat: 41.8012,
    lng: -72.8601,
    phone: '(860) 678-7996',
    website: 'https://route44cycles.com',
    email: null,
    brands_carried: ['Santa Cruz', 'Trek', 'Giant', 'Yeti', 'Fox', 'SRAM', 'Shimano'],
    services: ['repair', 'custom_builds', 'wheel_building', 'fitting'],
    shop_type: 'indie',
    verified: true,
  },
  {
    id: 'rr-cycles-putnam',
    name: 'R&R Cycles',
    address: '183 Providence St',
    city: 'Putnam',
    state: 'CT',
    zip: '06260',
    lat: 41.9167,
    lng: -71.9012,
    phone: '(860) 928-7864',
    website: null,
    email: null,
    brands_carried: ['Trek', 'Specialized', 'Electra', 'Shimano'],
    services: ['repair', 'rental'],
    shop_type: 'indie',
    verified: false,
  },
  {
    id: 'rei-manchester',
    name: 'REI',
    address: '65 Sycamore St',
    city: 'Manchester',
    state: 'CT',
    zip: '06040',
    lat: 41.7790,
    lng: -72.5249,
    phone: '(860) 648-0660',
    website: 'https://rei.com',
    email: null,
    brands_carried: ['Co-op Cycles', 'Trek', 'Specialized', 'Shimano', 'SRAM'],
    services: ['repair', 'rental', 'fitting'],
    shop_type: 'co-op',
    verified: true,
  },
  {
    id: 'bicycle-rack-new-haven',
    name: 'The Bicycle Rack',
    address: '315 Whalley Ave',
    city: 'New Haven',
    state: 'CT',
    zip: '06511',
    lat: 41.3084,
    lng: -72.9399,
    phone: '(203) 624-0444',
    website: 'https://bicyclerack.com',
    email: null,
    brands_carried: ['Trek', 'Cannondale', 'Giant', 'Shimano', 'SRAM'],
    services: ['repair', 'wheel_building', 'fitting'],
    shop_type: 'indie',
    verified: true,
  },
];

export function getShopsNear(lat, lng, radiusMiles) {
  const R = 3958.8;
  return SEED_SHOPS
    .map(shop => {
      const dLat = (shop.lat - lat) * Math.PI / 180;
      const dLng = (shop.lng - lng) * Math.PI / 180;
      const a = Math.sin(dLat / 2) ** 2 +
        Math.cos(lat * Math.PI / 180) * Math.cos(shop.lat * Math.PI / 180) *
        Math.sin(dLng / 2) ** 2;
      const distance = R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
      return { ...shop, distance: Math.round(distance * 10) / 10 };
    })
    .filter(shop => shop.distance <= radiusMiles)
    .sort((a, b) => a.distance - b.distance);
}
